
services:
  website:
    build: .
    container_name: clr_via
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./:/app # Mount the project directory as a volume
      - /app/node_modules
    command: yarn run dev # Start the development server with hot reloading
    develop:
      watch:
        - action: sync
          path: .
          target: .
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json